version: 0.1

log:
  level: info

storage:
  filesystem:
    rootdirectory: /var/lib/registry

http:
  addr: :5000

auth:
  token:
    realm: http://127.0.0.1:18080/token
    service: registry
    issuer: registry-auth
    rootcertbundle: /certs/token.crt
